CC = cl.exe
LINK = link.exe
LIB = lib.exe
CFLAGS = /c /O2 /W4 /Iinclude /DNO_ASM 

all: libxhash.lib

OBJEXT = .obj
include Makefile.inc

.c.obj:
  $(CC) /nologo $(CFLAGS) /Fo$*.obj $*.c

libxhash.lib: $(c_objects)
  $(LIB) /nologo /out:libxhash.lib $(c_objects)

test_xhash.exe: libxhash.lib tests/test_xhash.obj tests/sha_test.obj
	$(LINK) /nologo $<

check: test_xhash.exe
	test_xhash.exe

clean:
  del /S *.obj *.lib

rebuild: clean all

