CC = cl.exe
LIB = lib.exe
CFLAGS = /c /O2 /W4 /Iinclude /DNO_ASM 

all: libxhash.lib

OBJEXT = .obj
include Makefile.inc

.c.obj:
  $(CC) /nologo $(CFLAGS) /Fo$*.obj $*.c

libxhash.lib: $(c_objects)
  $(LIB) /nologo /out:libxhash.lib $(c_objects)

clean:
  del /S *.obj *.lib

rebuild: clean all

