name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  linux-x86-64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - run: sudo apt-get install gcc-multilib

    - run: make rebuild install test prefix=install64 ARCH=x86_64
    - run: make rebuild install test prefix=install32 ARCH=x86
