name: make

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  linux64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - run: make rebuild install test prefix=${{ github.workspace }}install CONFIG=linux64
    - run: make rebuild install test prefix=${{ github.workspace }}install CONFIG=linux64 NO_ASM=1

  linux32:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - run: sudo apt-get install gcc-multilib

    - run: make rebuild install test prefix=${{ github.workspace }}install CONFIG=linux32
    - run: make rebuild install test prefix=${{ github.workspace }}install CONFIG=linux32 NO_ASM=1

  linux-cross-compile-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - run: |
        sudo apt-get install gcc-aarch64-linux-gnu

    - run: make rebuild install prefix=${{ github.workspace }}installaarch64 CONFIG=linuxaarch64
    - run: make rebuild install prefix=${{ github.workspace }}installaarch64 CONFIG=linuxaarch64 NO_ASM=1
