name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  linux-x86-64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - run: |
        sudo apt-get install gcc-multilib 

    - run: make rebuild install test PREFIX=install64 ARCH=x86_64 USE_ASM=1
    - run: make rebuild install test PREFIX=install64 ARCH=x86_64 USE_ASM=0
    - run: make rebuild install test PREFIX=install32 ARCH=x86 USE_ASM=1
    - run: make rebuild install test PREFIX=install32 ARCH=x86 USE_ASM=0

  linux-cross-compile-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - run: |
        sudo apt-get install gcc-10-aarch64-linux-gnu

    - run: make rebuild install PREFIX=installaarch64 ARCH=aarch64 USE_ASM=1
    - run: make rebuild install PREFIX=installaarch64 ARCH=aarch64 USE_ASM=0
