name: Test cmake

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - run: sudo apt-get install gcc-multilib lib32stdc++6

    - run: cmake -B out-x64 -DCMAKE_INSTALL_PREFIX=install/x64
    - run: ninja -C out-x64
    - run: ninja -C out-x64 install
    - run: ninja -C out-x64 test
