name: make

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  linux64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - run: make rebuild install test prefix=${{ github.workspace }}install CONFIG=linux64
    - run: make rebuild install test prefix=${{ github.workspace }}install CONFIG=linux64 NO_ASM=1

  linux32:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - run: sudo apt-get install gcc-multilib

    - run: make rebuild install test prefix=${{ github.workspace }}install CONFIG=linux32
    - run: make rebuild install test prefix=${{ github.workspace }}install CONFIG=linux32 NO_ASM=1

  macosx:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6

    - run: make rebuild install test prefix=${{ github.workspace }}install CONFIG=macosx64
    - run: make rebuild install test prefix=${{ github.workspace }}install CONFIG=macosx64 NO_ASM=1

    - run: make rebuild install prefix=${{ github.workspace }}installarm CONFIG=macosxaarch64
    - run: make rebuild install prefix=${{ github.workspace }}installarm CONFIG=macosxaarch64 NO_ASM=1

  linux-cross-compile-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - run: |
        sudo apt-get install qemu-user qemu-user-static gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu binutils-aarch64-linux-gnu-dbg build-essential

    - run: make rebuild install prefix=${{ github.workspace }}installaarch64 CONFIG=linuxaarch64
    - run: qemu-aarch64 -L /usr/aarch64-linux-gnu "make test CONFIG=linuxaarch64"

    - run: make rebuild install prefix=${{ github.workspace }}installaarch64 CONFIG=linuxaarch64 NO_ASM=1
    - run: qemu-aarch64 -L /usr/aarch64-linux-gnu "make test CONFIG=linuxaarch64 NO_ASM=1"
