name: Test packages

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  vcpkg-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - run: sudo apt-get install gcc-multilib

    - run: vcpkg install xdigest --head --overlay-ports packages/vcpkg --triplet x64-linux --enforce-port-checks
    - run: vcpkg install xdigest --head --overlay-ports packages/vcpkg --triplet x86-linux --enforce-port-checks

  archlinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Validate package
      uses: heyhusen/archlinux-package-action@v3.0.0
      with:
        path: packages/archlinux
