name: Test packages

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  vcpkg-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - run: sudo apt-get install gcc-multilib lib32stdc++6

    - run: make test-vcpkg VCPKG_TRIPLET=x64-linux
    - run: make test-vcpkg VCPKG_TRIPLET=x64-linux NO_ASM=1

    # vcpkg refuses to cross compile without C++ which doesn't work either
    # - run: make test-vcpkg VCPKG_TRIPLET=x86-linux
    # - run: make test-vcpkg VCPKG_TRIPLET=x86-linux NO_ASM=1

  vcpkg-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6

    - run: make test-vcpkg VCPKG_TRIPLET=x64-osx
    - run: make test-vcpkg VCPKG_TRIPLET=x64-osx NO_ASM=1

    - run: make test-vcpkg VCPKG_TRIPLET=arm64-osx
    - run: make test-vcpkg VCPKG_TRIPLET=arm64-osx NO_ASM=1

  vcpkg-win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6

    - run: make test-vcpkg VCPKG_TRIPLET=x64-windows
    - run: make test-vcpkg VCPKG_TRIPLET=x64-windows NO_ASM=1

    - run: make test-vcpkg VCPKG_TRIPLET=x86-windows
    - run: make test-vcpkg VCPKG_TRIPLET=x86-windows NO_ASM=1

    - run: make test-vcpkg VCPKG_TRIPLET=x64-windows-static
    - run: make test-vcpkg VCPKG_TRIPLET=x64-windows-static NO_ASM=1

    - run: make test-vcpkg VCPKG_TRIPLET=x86-windows-static
    - run: make test-vcpkg VCPKG_TRIPLET=x86-windows-static NO_ASM=1

    - run: make test-vcpkg VCPKG_TRIPLET=x64-windows-static-md
    - run: make test-vcpkg VCPKG_TRIPLET=x64-windows-static-md NO_ASM=1

    - run: make test-vcpkg VCPKG_TRIPLET=x86-windows-static-md
    - run: make test-vcpkg VCPKG_TRIPLET=x86-windows-static-md NO_ASM=1

    - run: make test-vcpkg VCPKG_TRIPLET=arm64-windows NO_ASM=1
    - run: make test-vcpkg VCPKG_TRIPLET=arm64-uwp NO_ASM=1

    - run: make test-vcpkg VCPKG_TRIPLET=x64-uwp
    - run: make test-vcpkg VCPKG_TRIPLET=x64-uwp NO_ASM=1

  archlinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Validate package
      uses: heyhusen/archlinux-package-action@v3.0.0
      with:
        path: contrib/archlinux
