name: Test packages

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  vcpkg-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - run: sudo apt-get install gcc-multilib

    - run: make test-vcpkg VCPKG_TRIPLET=x64-linux
    - run: make test-vcpkg VCPKG_TRIPLET=x64-linux NO_ASM=1
    - run: make test-vcpkg VCPKG_TRIPLET=x86-linux
    - run: make test-vcpkg VCPKG_TRIPLET=x86-linux NO_ASM=1

  archlinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Validate package
      uses: heyhusen/archlinux-package-action@v3.0.0
      with:
        path: packages/archlinux
